name: bommeong
description: Sleep and Liver Care Management Application
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
    sdk: ">=3.1.3 <4.0.0"

dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter
    collection: any
    cupertino_icons: ^1.0.2
    flutter_native_splash: ^2.3.6
    flutter_dotenv: ^5.1.0
    flutter_launcher_icons: ^0.13.1
    get: ^4.6.6
    flutter_svg: ^2.0.9
    intl: ^0.19.0
    infinite_scroll_pagination: ^4.0.0
    hand_signature: ^3.0.2
    flutter_pdfview: ^1.3.2
    path_provider: ^2.1.2
    smooth_page_indicator: ^1.1.0
    flutter_chat_ui: ^1.6.12
    flutter_chat_types: ^3.6.2
    uuid: ^4.3.3
    image_picker: ^1.0.7
    shared_preferences: ^2.2.2
    flutter_secure_storage: ^9.2.2
    rive: ^0.13.1
    webview_flutter: ^4.0.7
    foundation: ^0.0.5
    daum_postcode_search: ^0.0.2
    sign_in_with_apple: ^6.1.1
    kakao_flutter_sdk: ^1.9.5

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^4.0.0
    intl_translation: ^0.20.0

flutter:
    uses-material-design: true

    assets:
        - assets/images/
        - assets/icons/
        - assets/config/.env
        - assets/data/
        - assets/images/home/
        - assets/images/login/
        - assets/images/chat/
        - assets/images/my/
        - assets/images/like/
        - assets/data/signtest.pdf
        - assets/images/my/miniDog.png
        - assets/images/like/standDog.svg
        - assets/images/my/dog.svg

    fonts:
        - family: Pretendard
          fonts:
              - asset: assets/fonts/Pretendard/Pretendard-Thin.otf
                weight: 100
              - asset: assets/fonts/Pretendard/Pretendard-ExtraLight.otf
                weight: 200
              - asset: assets/fonts/Pretendard/Pretendard-Light.otf
                weight: 300
              - asset: assets/fonts/Pretendard/Pretendard-Regular.otf
                weight: 400
              - asset: assets/fonts/Pretendard/Pretendard-Medium.otf
                weight: 500
              - asset: assets/fonts/Pretendard/Pretendard-SemiBold.otf
                weight: 600
              - asset: assets/fonts/Pretendard/Pretendard-Bold.otf
                weight: 700
              - asset: assets/fonts/Pretendard/Pretendard-ExtraBold.otf
                weight: 800
              - asset: assets/fonts/Pretendard/Pretendard-Black.otf
                weight: 900

        - family: Inter
          fonts:
              - asset: assets/fonts/Inter/Inter-Thin.ttf
                weight: 100
              - asset: assets/fonts/Inter/Inter-ExtraLight.ttf
                weight: 200
              - asset: assets/fonts/Inter/Inter-Light.ttf
                weight: 300
              - asset: assets/fonts/Inter/Inter-Regular.ttf
                weight: 400
              - asset: assets/fonts/Inter/Inter-Medium.ttf
                weight: 500
              - asset: assets/fonts/Inter/Inter-SemiBold.ttf
                weight: 600
              - asset: assets/fonts/Inter/Inter-Bold.ttf
                weight: 700
              - asset: assets/fonts/Inter/Inter-ExtraBold.ttf
                weight: 800
              - asset: assets/fonts/Inter/Inter-Black.ttf
                weight: 900
